# Generated by Django 4.2 on 2024-09-12 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsulot_nomi', models.CharField(max_length=255)),
                ('sotiladigan_narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miqdori', models.PositiveIntegerField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='maxsulotlar_rasm/')),
                ('sana', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsulot_nomi', models.CharField(max_length=255)),
                ('maxsulot_sotib_olingan_narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maxsulot_soni', models.PositiveIntegerField()),
                ('sotilishi_kutulyotgan_narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='partiya_rasm/')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsulotning_jami_summasi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qarz_summa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('maxsulotlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maxsulotlar')),
            ],
        ),
        migrations.CreateModel(
            name='Xaridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=15)),
                ('manzil', models.CharField(max_length=255)),
                ('ummumiy_savdo', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('qarzdorlik', models.BooleanField(blank=True, default=False, null=True)),
                ('qarz_miqdori', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SotuvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxsulot_soni', models.PositiveIntegerField()),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.maxsulotlar')),
                ('sotuv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sotuv')),
            ],
        ),
        migrations.AddField(
            model_name='sotuv',
            name='xaridor_ismi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.xaridor'),
        ),
        migrations.CreateModel(
            name='QarzlarniSondirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tolangan_miqdor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('toliq_tolash', models.BooleanField(default=False)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.xaridor')),
            ],
        ),
    ]
