# Generated by Django 4.2.14 on 2024-08-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('olingan_narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dona', models.IntegerField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Xaridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('telefon_raqami', models.CharField(max_length=20)),
                ('oladigan_maxsulot_soni', models.IntegerField()),
                ('umumiy_savdo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qarzdor', models.BooleanField(default=False)),
                ('maxsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('sotilgan_dona', models.IntegerField()),
                ('sotilgan_narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qarzdor', models.BooleanField(default=False)),
                ('olingan_summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahsulot')),
                ('xaridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.xaridor')),
            ],
        ),
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dona', models.IntegerField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='warehouse_images/')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahsulot')),
            ],
        ),
        migrations.CreateModel(
            name='Partiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField()),
                ('umumiy_summa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qanchadan_olingani', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qanchadan_sotiladigani', models.DecimalField(decimal_places=2, max_digits=10)),
                ('keladigan_maxsulot_soni', models.IntegerField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='batch_images/')),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mahsulot')),
            ],
        ),
    ]
